# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [8]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
a=np.zeros(10)
print(a)
np.size(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


10

3. Create a vector with values ranging from 10 to 49

In [6]:
b=np.arange(10,49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [7]:
np.shape(b)

(39,)

5. Print the type of the previous array in question 3

In [8]:
type(b)

numpy.ndarray

6. Print the numpy version and the configuration


In [19]:
print(np.__version__, np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/python\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/python\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/python\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/python\\Library\\include']
1.19.2 None


7. Print the dimension of the array in question 3


In [9]:
np.ndim(b)

1

8. Create a boolean array with all the True values

In [17]:
c=np.arange(1,11)
c.astype("bool")

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [18]:
np.random.randint(20,size=(3,4))

array([[ 0, 12,  4,  8],
       [10, 18, 15, 19],
       [ 0, 11,  0,  7]])

10. Create a three dimensional array



In [20]:
np.random.randint(100,size=(2,4,5))


array([[[ 7, 90, 62, 58, 60],
        [15, 81,  2, 59, 79],
        [15, 76, 47, 90, 55],
        [80, 22, 93, 59, 43]],

       [[71, 48, 79, 37, 45],
        [16, 29,  4,  5, 47],
        [33, 63,  4, 43, 80],
        [69,  4,  4, 69, 54]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [21]:
d=np.arange(1,15)
d=d[::-1]
d

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [22]:
null=np.zeros((10))
null[4]=1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [23]:
iden=np.eye(3,3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [10]:
e=np.array([6,7,8,9,10])
e1=e.astype("float32")
e1

array([ 6.,  7.,  8.,  9., 10.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [11]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [12]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [14]:
arr10=np.arange(0,9)
odd1=np.extract(arr10%2,arr10)
odd1

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array

In [55]:
arr10=np.arange(0,9)
rep=np.extract(arr10%2,arr10)
print(rep)
rep[0:]=-1
rep


[1 3 5 7]


array([-1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [17]:
f=np.arange(10)
f[5:9]=12
f

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [18]:
g=np.ones((4,4))
g[1:-1,1:-1]=0
g

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [19]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1:-1,1:-1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [20]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [22]:
a2d=np.arange(0,9)
h=a2d.reshape(3,3)
print(h)
h[0]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [23]:
a2d=np.arange(0,9)
h=a2d.reshape(3,3)
print(h)
h[1,1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
a2d=np.arange(0,9)
h=a2d.reshape(3,3)
print(h)
h[0:2,-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
i=np.random.randint(40,size=(10,10))
print(i)
print(np.max(i))
np.min(i)

[[32 37 10  3 38 10 39 26 25 22]
 [24 36 29 26 20 29 17  5 25 30]
 [17  3 27  0 21 34 27 21  8 11]
 [ 9 36 20 37  9  0  9 23  6 33]
 [25 26  8 17 35 37 12 27 11 26]
 [35 32  7 23 31  4 16  7 19 34]
 [ 2 15 20 22 12 26 17 21  5  4]
 [28 22 34  0 19 19  3  5 10 36]
 [29  4 16 28 30 24 33 14  6  8]
 [21 37 39  3 16 22 32 23 32 37]]
39


0

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [29]:
a= np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.extract(a==b,a)

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data
np.extract(names!="Will",data)


array([-0.22865981, -1.54623304,  2.12847046, -0.34804566,  2.41331352])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [34]:
b2d=np.random.uniform(1.0,15.0,size=(5,3))
b2d

array([[ 3.79275897,  4.39951938, 11.71492789],
       [13.97052085,  6.93408671,  6.89142763],
       [ 6.75215174,  5.87253556, 10.93831096],
       [ 8.20366676,  3.7310374 ,  2.14700115],
       [13.59929908, 14.41782647,  3.79997283]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [35]:
b3d=np.random.uniform(1.0,16.0,size=(2,2,4))
b3d

array([[[13.29548043,  8.47260796,  2.42502251,  9.0224899 ],
        [ 7.28786597,  1.11297187, 15.80084442,  9.99559117]],

       [[ 3.98689335,  9.19415927,  3.9112296 , 13.30043653],
        [15.44988676, 13.60056627,  6.48751418, 10.16843721]]])

33. Swap axes of the array you created in Question 32

In [36]:
np.swapaxes(b3d,0,1)

array([[[13.29548043,  8.47260796,  2.42502251,  9.0224899 ],
        [ 3.98689335,  9.19415927,  3.9112296 , 13.30043653]],

       [[ 7.28786597,  1.11297187, 15.80084442,  9.99559117],
        [15.44988676, 13.60056627,  6.48751418, 10.16843721]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [41]:
x1=np.arange(12,31,2)
print(x1)
np.sqrt(x1)

[12 14 16 18 20 22 24 26 28 30]


array([3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595,
       4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [43]:
z1=np.random.randint(12,size=(6))
print(z1)
z2=np.random.randint(12,size=(6))
print(z2)
np.maximum(z1,z2)

[7 2 5 6 5 6]
[4 7 1 8 6 1]


array([7, 7, 5, 8, 6, 6])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [45]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(names))
np.unique(names)

['Bob' 'Bob' 'Joe' 'Joe' 'Joe' 'Will' 'Will']


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [46]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.extract(a!=5,a)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [49]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray[0:,-1]=10
sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [50]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [53]:
y2=np.random.randint(5,size=(5,4))
print(y2)
y2.cumsum()

[[2 1 1 0]
 [3 0 3 3]
 [1 3 4 4]
 [4 2 4 1]
 [4 3 3 1]]


array([ 2,  3,  4,  4,  7,  7, 10, 13, 14, 17, 21, 25, 29, 31, 35, 36, 40,
       43, 46, 47], dtype=int32)