# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
a=np.arange(0,10)
print(a)
a.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
b=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b1=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])             
np.vstack((b,b1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:
c=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
c1=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((c,c1))


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [13]:
d=np.arange(0,10)
print(d.reshape(5,2))
d.ravel()


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [15]:
e=np.arange(0,15)
print(e.reshape(1,3,5))
e.flatten()

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [18]:
f=np.arange(0,15)
print(f)
f.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [35]:
g=np.arange(25)
g1=g.reshape(5,5)
print(g1)
np.square(g1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [3]:
h=np.arange(21,51)
h1=h.reshape(5,6)
print(h1)
h1.mean()

[[21 22 23 24 25 26]
 [27 28 29 30 31 32]
 [33 34 35 36 37 38]
 [39 40 41 42 43 44]
 [45 46 47 48 49 50]]


35.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [32]:
np.std(h1)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [4]:
np.median(h1)

35.5

## Question:11

### Find the transpose of the previous array in Q8?

In [5]:
print(h1)
h1.transpose()

[[21 22 23 24 25 26]
 [27 28 29 30 31 32]
 [33 34 35 36 37 38]
 [39 40 41 42 43 44]
 [45 46 47 48 49 50]]


array([[21, 27, 33, 39, 45],
       [22, 28, 34, 40, 46],
       [23, 29, 35, 41, 47],
       [24, 30, 36, 42, 48],
       [25, 31, 37, 43, 49],
       [26, 32, 38, 44, 50]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [45]:
j=np.arange(1,17)
j1=j.reshape(4,4)
print(j1)
j1.trace()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


34

## Question:13

### Find the determinant of the previous array in Q12?

In [47]:
np.linalg.det(j1)

4.7331654313261276e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [49]:
arr=np.random.randint(100,size=(5,5))
print(arr)
a=np.percentile(arr,5)
print("this is 5th percentile =",a)
b=np.percentile(arr,95)
print("this is 95th percentile =",b)

[[42 51 39 78 29]
 [59 12 94 88 84]
 [48 65 18 61  9]
 [ 1  2 60 31 61]
 [87  5 53 54 79]]
this is 5th percentile = 2.6000000000000005
this is 95th percentile = 87.8


## Question:15

### How to find if a given array has any null values?

In [53]:
array=np.array([[3,0,1,0,4],[7,76,0,0,3],[0,6,54,4,0]])
print(array)
array==0

[[ 3  0  1  0  4]
 [ 7 76  0  0  3]
 [ 0  6 54  4  0]]


array([[False,  True, False,  True, False],
       [False, False,  True,  True, False],
       [ True, False, False, False,  True]])